name: fiap-mechanics

services:
  dotnet:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=2%r6dZ6Xk@g3
      - TZ=America/Sao_Paulo
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql

volumes:
  mssql:
    name: fiap-mechanics-mssql
