name: fiap-mechanics

services:
  dotnet:
    build: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=mssql;Database=fiap-mechanics;User Id=sa;Password=2%r6dZ6Xk@g3;TrustServerCertificate=True;
      - EmailSenderOptions__SmtpServer=mailpit
      - Application__Version=local
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://datadog-agent:4317
    ports:
      - "5000:8080"
    volumes:
      - dotnet:/home/app
    depends_on:
      mssql:
        condition: service_healthy
      mailpit:
        condition: service_healthy
      datadog-agent:
        condition: service_healthy

  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=2%r6dZ6Xk@g3
      - TZ=America/Sao_Paulo
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql
    healthcheck:
      test: '/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1"'
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  mailpit:
    image: axllent/mailpit:v1.28
    environment:
      - MP_DATABASE=/data/mailpit.db
      - MP_MAX_AGE=7d
      - TZ=America/Sao_Paulo
      - MP_SMTP_AUTH=postmaster@mechanics.com:xFCsMj6a4NWbZgr5
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailpit:/data
    healthcheck:
      test: 'wget --spider -q http://localhost:8025/api/v1/info'
      interval: 2s
      timeout: 5s
      retries: 10
  
  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    environment:
      - DD_API_KEY=${DD_API_KEY:?}
      - DD_SITE=us5.datadoghq.com
      - DD_ENV=dev
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_TRACES_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true      
      - DD_CONTAINER_EXCLUDE=name:datadog-agent
    ports:
      - "4317:4317"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    healthcheck:
      test: ["CMD-SHELL", "agent health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  dotnet:
    name: fiap-mechanics-dotnet
  mssql:
    name: fiap-mechanics-mssql
  mailpit:
    name: fiap-mechanics-mailpit
