apiVersion: v1
kind: Secret

metadata:
  name: fiap-mechanics-secrets

type: Opaque
stringData:
  ConnectionStrings__Default: "aws:secretsmanager:fiap-mechanics/database"
  EmailSenderOptions__UserName: "aws:secretsmanager:fiap-mechanics/email:userName"
  EmailSenderOptions__Password: "aws:secretsmanager:fiap-mechanics/email:password"
