app:
  name: fiap-mechanics
  version: 1.0.0
  env: dev
  port: 5000
  autoRunMigrations: true

image:
  repository: 000.dkr.ecr.us-east-1.amazonaws.com/fiap-mechanics-dev-cr
  tag: latest

database:
  connectionString: "Server=000.us-east-1.rds.amazonaws.com;Database=fiap-mechanics;User Id=xxx;Password=xxx;"

email:
  smtpServer: fiap-mechanics-dev-email-smtp-lb-000.elb.us-east-1.amazonaws.com
  smtpPort: 1025
  userName: "xxx@mechanics.com"
  password: "xxx"
  sslRequired: false
  senderName: FIAP Mechanics
  senderAddress: "postmaster@mechanics.com"
