<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>

    <SatelliteResourceLanguages>pt-BR</SatelliteResourceLanguages>

    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
      <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.4" />
      <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="8.0.3" />
    
      <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
      <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
      <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.0" />
      <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
      <PackageReference Include="Serilog.Enrichers.Span" Version="3.1.0" />
      <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
      <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    
      <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.11.2" />
      <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.11.1" />
      <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.11.1" />
      <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.11.0-beta.1" />
      <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.11.1" />
      <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.11.2" />
      <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.11.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mechanics.Application\Mechanics.Application.csproj" />
    <ProjectReference Include="..\Mechanics.Domain\Mechanics.Domain.csproj" />
    <ProjectReference Include="..\Mechanics.Infra.CrossCutting.IoC\Mechanics.Infra.CrossCutting.IoC.csproj" />
    <ProjectReference Include="..\Mechanics.Infra.Data\Mechanics.Infra.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Condition="Exists('keys\jwt-public.pem')" Include="keys\jwt-public.pem">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
