apiVersion: external-secrets.io/v1
kind: ClusterSecretStore

metadata:
  name: "{{ .Values.app.name }}-aws-secrets"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-15"

spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            namespace: external-secrets
            key: access-key-id
          secretAccessKeySecretRef:
            name: aws-credentials
            namespace: external-secrets
            key: secret-access-key
          sessionTokenSecretRef:
            name: aws-credentials
            namespace: external-secrets
            key: session-token
