apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Values.app.name }}-configs

data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.app.environmentName | quote }}
  EmailSenderOptions__SslRequired: {{ .Values.email.sslRequired | quote }}
  EmailSenderOptions__SenderInformation__Name: {{ .Values.email.senderName | quote }}
  EmailSenderOptions__SenderInformation__Address: {{ .Values.email.senderAddress | quote }}
