apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: {{ .Values.app.name }}-email

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: "{{ .Values.app.name }}-aws-secrets"
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.name }}-email
  data:
    - secretKey: userName
      remoteRef:
        key: "{{ .Values.app.name }}-{{ .Values.app.env }}-email"
        property: userName
    - secretKey: password
      remoteRef:
        key: "{{ .Values.app.name }}-{{ .Values.app.env }}-email"
        property: password
