apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ .Values.app.name }}
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: {{ ternary .Values.app.name (printf "%s-%s" .Values.app.name .Values.app.env) (eq .Values.app.env "prod") }}

spec:
  ingressClassName: {{ .Values.app.name }}-alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: {{ .Values.app.port }}
