name: Export artifact

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          cache: true
          cache-dependency-path: |
            src/**/packages.lock.json
            tests/**/packages.lock.json
          global-json-file: global.json

      - name: Restore dependencies
        run: dotnet restore --locked-mode

      - name: Publish artifact
        run: dotnet publish -c Release -o ./dist --no-restore

      - name: Create compressed file
        run: zip -r -9 dist.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: build
          path: ./dist.zip
