name: Push to ECR

on:
  workflow_call:
    inputs:
      environment:
        description: Deployment environment (dev|stg|prod)
        required: true
        type: string

jobs:
  deploy-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get ECR Repository URI
        run: echo "REPOSITORY_URI=$(aws ecr describe-repositories --repository-names fiap-mechanics-${{ inputs.environment }}-cr --query 'repositories[0].repositoryUri' --output text)" >> $GITHUB_ENV

      - name: Install Helm Chart
        run: |
          aws eks update-kubeconfig --name fiap-mechanics-${{ inputs.environment }}-cluster --region us-east-1
          helm upgrade --install fiap-mechanics ./k8s
            --set image.repository=$REPOSITORY_URI \
            --set image.tag=${{ github.sha }} \
            --set app.env=${{ inputs.environment }}
